name: Swapsys PyPi Package Upload 

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo content
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        
    - name: Build package
      run: python -m build --verbose  # Enable verbose output
      
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.API_TOKEN }}
        
    - name: Confirm package publication
      run: echo "Package has been published to PyPI successfully!"
